import {
  LayoutDashboard, Users, UserCog, ArrowDownToLine, ArrowUpFromLine, Wallet,
  QrCode, Percent, FileCheck2, ScrollText, CreditCard, History,
  FilePlus2, KeyRound, DatabaseBackup, Crown, FileText, Layers, Landmark,
  Settings, FolderOpen, ClipboardList,
} from "lucide-react";

/** Static navigation map per role — referenced by DashboardLayout. */
export const NAV = {
  admin: [
    { to: "/admin", label: "Dashboard", icon: LayoutDashboard, end: true },
    { to: "/admin/master-distributors", label: "Master Distributors", icon: Crown },
    { to: "/admin/distributors", label: "Distributors", icon: Users },
    { to: "/admin/agents", label: "Agents", icon: UserCog },
    { to: "/admin/recharges", label: "QR Approvals", icon: ArrowDownToLine },
    { to: "/admin/withdrawals", label: "Pay Withdrawals", icon: ArrowUpFromLine },
    { to: "/admin/transactions", label: "CC Bill Request", icon: CreditCard },
    { to: "/admin/live-bill-history", label: "Live Bill History", icon: History },
    { to: "/admin/statement", label: "Admin Statement", icon: ScrollText },
    { to: "/admin/qrcodes", label: "QR Codes", icon: QrCode },
    { to: "/admin/qr-name-entry", label: "QR Name Entry", icon: FileText },
    { to: "/admin/qr-gallery", label: "QR Gallery", icon: FolderOpen },
    { to: "/admin/headlines", label: "Add Announcement", icon: ScrollText },
    { to: "/admin/commission", label: "Set Commission", icon: Percent },
    { to: "/admin/service-slabs", label: "Service Slabs", icon: Layers },
    { to: "/admin/banks", label: "Bank Entry", icon: Landmark },
    { to: "/admin/cc-billers", label: "CC Billers", icon: Landmark },
    { to: "/admin/kyc", label: "KYC Requests", icon: FileCheck2 },
    { to: "/admin/reasons", label: "Reason Entry", icon: ClipboardList },
    { to: "/admin/audit", label: "Audit Logs", icon: ScrollText },
    { to: "/admin/change-password", label: "Change Password", icon: KeyRound },
    { to: "/admin/admins", label: "Admin Management", icon: Users },
    { to: "/admin/settings", label: "Settings", icon: Settings },
    { to: "/admin/policies", label: "Rules & Policies", icon: ScrollText },
  ],
  master_distributor: [
    { to: "/md", label: "Dashboard", icon: LayoutDashboard, end: true },
    { to: "/md/distributors", label: "My Distributors", icon: Users },
    { to: "/md/recharges", label: "Agent QR Requests", icon: ArrowDownToLine },
    { to: "/md/withdrawal", label: "Pay Withdrawal", icon: ArrowUpFromLine },
    { to: "/md/change-password", label: "Change Password", icon: KeyRound },
    { to: "/md/change-mpin", label: "Change MPIN", icon: KeyRound },
    { to: "/md/policies", label: "Rules & Policies", icon: ScrollText },
  ],
  distributor: [
    { to: "/distributor", label: "Dashboard", icon: LayoutDashboard, end: true },
    { to: "/distributor/agents", label: "My Agents", icon: UserCog },
    { to: "/distributor/recharges", label: "Agent QR Requests", icon: ArrowDownToLine },
    { to: "/distributor/withdrawal", label: "Pay Withdrawal", icon: ArrowUpFromLine },
    { to: "/distributor/change-password", label: "Change Password", icon: KeyRound },
    { to: "/distributor/change-mpin", label: "Change MPIN", icon: KeyRound },
    { to: "/distributor/policies", label: "Rules & Policies", icon: ScrollText },
  ],
  agent: [
    { to: "/agent", label: "Dashboard", icon: LayoutDashboard, end: true },
    { to: "/agent/recharge", label: "QR Load Wallet", icon: FilePlus2 },
    { to: "/agent/billpay", label: "Credit Card Bill", icon: CreditCard },
    { to: "/agent/live-billpay", label: "Live Bill Pay", icon: CreditCard },
    { to: "/agent/live-billpay/history", label: "Live Bill History", icon: History },
    { to: "/agent/ledger", label: "Account Statement", icon: ScrollText },
    { to: "/agent/withdrawal", label: "Pay Withdrawal", icon: ArrowUpFromLine },
    { to: "/agent/change-password", label: "Change Password", icon: KeyRound },
    { to: "/agent/change-mpin", label: "Change MPIN", icon: KeyRound },
    { to: "/agent/change-tpin", label: "Manage TPIN", icon: KeyRound },
    { to: "/agent/policies", label: "Rules & Policies", icon: ScrollText },
  ],
};
